### ISSUE TITLE
CosmosDB Module having issues in Azure Functions

### ISSUE THREAD

**Issue by Rabbit994** [PlagueHO/CosmosDB#290]
# Issue

Before submitting your issue for the CosmosDB project, please take a moment to provide the following details:

- [ ] Powershell Core 6.2
- [ ] Azure Functions v2
- [ ] According to $PSVersionTable, "OS": "Microsoft Windows 10.0.14393 
- [ ] Version of CosmosDB PowerShell Module: 3.2.3.359  CosmosDB

See error log here: https://gist.github.com/Rabbit994/930ff415dd9113a8c1b8dd8e51cab96c

**Comment by PlagueHO** [comment]
Hi @Rabbit994 - thanks for raising this. I had meant to actually write a blog post on using CosmosDB module is Azure Functions v2.

It looks like the problem is caused by using the `Add-Type` to create and compile some custom class definitions (`[CosmosDB.Context]` etc.). `Add-Type` uses reflection to compile the classes but it seems like it can't find some of the files for the .NET Core 2.1.

Unfortunately native PowerShell classes don't support Namespaces, so I have to use reflection. Might be something that will need to be raised with the PowerShell team.

**Comment by Rabbit994** [comment]
When looking at Powershell Azure Function Github, I see this issue: https://github.com/Azure/azure-functions-powershell-worker/issues/220

Is that very similar to your problem?

**Comment by PlagueHO** [comment]
Hi @Rabbit994 - yep! That is the exact problem. Good catch. Great that it has been already logged. We will need to watch the progress.

**Comment by PlagueHO** [comment]
Hi @Rabbit994 - I've got an idea for a solution for this problem: Build the types as a native .NET Core assembly and ship that with the module. I'd just need to modify the build process a little bit. I'll work on it this weekend.

**Comment by Rabbit994** [comment]
I'd hate you for to do all that work. There has been some progress maybe on Azure side. I ended up switching my Function over to Python, which was whole another nightmare, for what I needed so it's not longer critical for me.

**Comment by PlagueHO** [comment]
It shouldn't be too much work (famous last words), so still might be worth doing. Besides that, I've been toying with the idea of moving the module over to C# to potentially make use of the DocumentDB SDK - so this could be a small experiment.

**Comment by invisibleaxm** [comment]
@PlagueHO , just curious if you made progress on your ^^ experiment :) I stumbled upon your CosmosDB module and found it very useful up until the point where I realized I couldn't use it inside azure functions which was my main use case.  I am curious if you have temporary work-arounds for setting/passing the context until this issue is fixed?

**Comment by PlagueHO** [comment]
Hi @invisibleaxm - I'm just finishing it. Just have a couple of things to test with it, but I'm aiming to have it done by end of the week.

**Comment by invisibleaxm** [comment]
That is awesome news! I started to rewrite my code to use the CosmosDB REST endpoints but i think is worth waiting for your updated code :)

Thanks again!

**Comment by PlagueHO** [comment]
I'm just releasing this to the PS Gallery as 3.3.0.0. I've not yet tested the changes in Azure Functions, but I'll aim to do that tomorrow.

**Comment by invisibleaxm** [comment]
Thanks again! I just noticed the version in PSGallery is still 3.2.4.376, as soon as 3.3.0.0 is there i can help with testing as well.

**Comment by PlagueHO** [comment]
Thanks @invisibleaxm - I just ran into a problem with the manifest (had some trailing whitespace that caused my PSSA tests to fail). So I'm just fixing that up and will release shortly (once all the tests are complete).

**Comment by PlagueHO** [comment]
@invisibleaxm - this new version is now on the PS Gallery: https://www.powershellgallery.com/packages/CosmosDB/3.3.0.405

I haven't yet had a chance to try in Azure Functions, but will try tomorrow. But if you get to it before me, keen to know if you it works OK.
