### ISSUE TITLE
Set-CosmosDbDocument return 404 not found

### ISSUE THREAD

**Issue by CharlesLi-debug** [PlagueHO/CosmosDB#349]
# Issue

Sorry, if I missed sth important.

Set-CosmosDbDocument return 404 not found but actually, with WHERE c.id = "xxx" 
I can find the document. 

At same time, if I use Get-CosmosDbDocument, it will retrun the same issue.
Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId 'preferences' -Id "6aa4389e-f126-4500-9a37-a11a6e7b13e5" -PartitionKey "emailaddress"

Anyone has the same issue?

**Comment by PlagueHO** [comment]
Hi @CharlesLi-debug - 

I'm not sure what is causing the issue with `Set-CosmosDbDocument` - I might need to get some more information on this: Can you get the document 'xxx' using `Get-CosmosDbDocument`?

Regarding the `Get-CosmosDbDocument` issue, this looks to be because you need to specify the actual partition key value in the `-PartitionKey` parameter:

```powershell
Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId 'preferences' -Id "6aa4389e-f126-4500-9a37-a11a6e7b13e5" -PartitionKey "someone@contoso.com"
```

**Comment by andrewbeaumont** [comment]
I have found that the Partition Key needs to be specified as an array:

`Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId directories -PartitionKey @("emailaddress")`

This is despite the fact that the parameter is specifying the type [System.Object[]]

**Comment by CharlesLi-debug** [comment]
Sorry, I forget to update this as I am busy on some projects.
Thank you for all the help.
It seems the property -Id is force required. And the ID needs to be converted to GUID: [Guid]
