### ISSUE TITLE
New-CosmosDbDocument does not allow create records with key names differ by case only

### ISSUE THREAD

**Issue by alexeymarkov** [PlagueHO/CosmosDB#413]
It is not possible to add records where key names differ by case only.
For example,
`
{
  "key": "value",
  "Key": "Value"
}
`
although this is a valid Cosmos Db document.

The problem is at line `ConvertFrom-Json`

**Comment by PlagueHO** [comment]
Thanks for raising this @alexeymarkov.

To fix this I might need to implement additional functions for just passing/returning raw JSON payloads instead of converting them to/from objects.

E.g.
New-CosmosDbDocumentJson
Set-CosmosDbDocumentJson

The `Get-CosmosDbDocumentJson` function already exists to address this problem.

I'll work on this tomorrow.

**Comment by PlagueHO** [comment]
Further on thinking on this, I might just add a `-ReturnJson` switch to the functions instead and document the purpose is to allow for this condition.
